### ISSUE TITLE
Strange behavior for Services section

### ISSUE THREAD

**Issue by divinerites** [themefisher/airspace-hugo#21]
I copied the demo site and the 8 items where rightly aligned.

I just changed some icons and text and suddenly the 5th item is in line 2 column 4 (same for the 10th).
The generated code seems clean, and is strictly the same for my 8 items.

I'm puzzled, did you already saw this "bad" behaviour ? ANy help/tip/pointer appreciated.

Work in progress result here : https://arolla-cocoon.netlify.com/

<img width="1530" alt="capture d ecran 2018-06-27 a 13 00 46" src="https://user-images.githubusercontent.com/32342823/41996756-bd713924-7a0a-11e8-9247-67fd41a9c5b1.png">

My code:

```
enable: true
title: Nos prestations / Our Services
subtitle: >
  Retrouvez le confort d'une chambre d'hôtel, en pleine nature et dans un lieu exceptionnel.
content:

  - icon: ion-coffee
    name: Epicerie/Boissons chaudes
    text: >
      Boissons chaudes et épicerie de produits locuax et Bios

  - icon: ion-compass
    name: Des promenades magiques
    text: >
      De nombreuses randonnées se font au départ d'Arolla. Tous les goûts et tous les niveaux !

  - icon: ion-bonfire
    name: Chauffage au bois / Wood Oven
    text: >
      Tout le bois nécessaire sera fourni pour profiter au maximum des joies du poële.

  - icon: ion-thermometer
    name: Douche & sanitaires
    text: >
      Douche chaude 1 CHF.

  - icon: ion-earth
    name: Des produits naturels
    text: >
      De l'eau exceptionnelement pure en direct du glacier, de nombreux produits locaux naturels.

  - icon: ion-leaf
    name: Respect de la nature
    text: >
      Nous utilisons exclusivement des produits nettoyants bios.

  - icon: ion-card
    name: Paiments faciles / Easy payments
    text: >
      Credit cards (Visa, Mastercard, Vpay, American express, Maestro), liquide/cash, Bank transferts.

  - icon: ion-cash
    name: Un prix très doux ... 55 CHF
    text: >
      Prix par nuit, tout inclus : Tent, King bed 2 personnes, poêle à bois, serviettes, vue, sourire, emplacement voiture, TVA, taxe de séjour.

```
