### ISSUE TITLE
AirSpace Theme - Portfolio Sub Image Issue

### ISSUE THREAD

**Issue by Paulser** [themefisher/airspace-hugo#27]
# AirSpace Theme - Portfolio Sub Image Issue

I asked the Hugo community forum for support and they suggested I raise an issue on Github for this theme. 

* [Hugo Forum - Original Post](https://discourse.gohugo.io/t/airspace-theme-portfolio-sub-image-categorys-issue-yml-file-review/12767)

## Issue Information 

This AirSpace template using image category to show off work portfolios. 

Using this template I can not figure out how to add more than one image/portfolios to one category. 

### Example of default code to edit existing images

To configure the images portfolios I reviewed the **work.yml** file under **data folder**. 

by default it looks somthing like this :

```

portfolio:
  - category: Brand
    url: "#"
    image: "/img/portfolio/work1.jpg"
    name: Test
    description: >
      Labore et dolore magna aliqua. Ut enim ad
      

  - category: Websites
    url: "#"
    image: "/img/portfolio/work1.jpg"
    name: Title 2
    description: >

    
  - category: Graphics
    image: "/img/portfolio/work2.jpg"
    url: "#"
    name: Title 2
    description: >
      Labore et dolore magna aliqua. Ut enim ad


  - category: Branding
    url: "#"
    image: "/img/portfolio/work3.jpg"
    name: Title 2
    description: >
      Labore et dolore magna aliqua. Ut enim ad
```
### Editing Code - Adding Category

So I can add additional category by copying the existing code and just changing the category name.
```
  - category: new Category
    url: "#"
    image: "/img/portfolio/NEW-IMAGE.jpg"
    name: New Title
    description: >
      Explain the work shown in image.

```
### Editing Code - Second Image Within Category Issue

The issue I have is I want to be able to add an additional image to existing Category.

I have tried to add a new image with existing Category name. This keeps the images within the same Category but shows two Category with the same name in the menu provided by the theme.

#### Code Example 
```
  - category: Graphics
    image: "/img/portfolio/work2.jpg"
    url: "#"
    name: Title 2
    description: >
      Labore et dolore magna aliqua. Ut enim ad

  - category: Graphics
    image: "/img/portfolio/work1.jpg"
    url: "#"
    name: Title 2
    description: >
      Labore et dolore magna aliqua. Ut enim ad
```
#### Code Example Result / Issue 

![peek 2018-07-28 14-46](https://user-images.githubusercontent.com/20326940/43357160-337d4586-9275-11e8-8ebc-fe50543056f4.gif)

# My Goal

![4893d54bb47da2911d90dd3ed5c0d9c69d91e3cd_1_690x321](https://user-images.githubusercontent.com/20326940/43357129-d793a4cc-9274-11e8-81f7-cd159a9093cc.gif)

# Disclaimer

I am a beginner so sorry for anything I might say that incorrect. 

Any help would be appreciated or pointing me in the right direction would be great.

Please ask any question you want if you require more information and I do my best to answer.

Thanks for reading this support issue. 

# Additional Resources Worth Reviewing

* [AirSpace - Hugo theme port - GitHub](https://github.com/themefisher/airspace-hugo)
* [AirSpace - jekyll theme](https://ndrewtl.github.io/airspace-jekyll/work/#)
* [Hugo Forum - Original Post](https://discourse.gohugo.io/t/airspace-theme-portfolio-sub-image-categorys-issue-yml-file-review/12767)
