### ISSUE TITLE
Numbered/Bulleted List miss bullets

### ISSUE THREAD

**Issue by njsss** [themefisher/airspace-hugo#80]
Hi there, I really like the theme but there's something wrong with the markdown style of bullet listing. E.g, I tried adding some numbered/bulleted list inside the .md file under the projection folder, however, it only shows the content and doesn't render any markdown bullets (such as "* " or "1. ") at all.

**Comment by divinerites** [comment]
You can add this kind of code to your personalised `css`. 
Locate what section you're on, and adapt it. Should work right away.

```css
  /* bullets */
  #TheSectionNameYouWantToHaveBullets ul li {
    color: #666;
    list-style-type: disc;
    margin-left: 30px;
  }
```
